version: '3'

volumes:
  postgres:

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    volumes:
      - .:/var/www/html
      - ./php:/usr/local/etc/php
    ports:
      - ${WEB_PORT}:80

  db:
    image: postgres:12
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./db/migrations:/var/lib/postgresql/migrations
      - ./db/fixtures:/var/lib/postgresql/fixtures
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_DEV_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DEV_DATABASE}
      - POSTGRES_USER=${POSTGRES_DEV_USER}
    ports:
      - ${POSTGRES_DEV_PORT}:5432
