version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    volumes:
      - ./app:/var/www/html/app
    ports:
      - ${WEB_PORT}:80

  db:
    image: postgres:12
    volumes:
      - ./db/data:/var/lib/postgresql/data
      - ./db/migrations:/var/lib/postgresql/migrations
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_DEV_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DEV_DATABASE}
      - POSTGRES_USER=${POSTGRES_DEV_USER}
    ports:
      - ${POSTGRES_DEV_PORT}:5432
