FROM php:8.1.5-apache

# set document root
ENV APACHE_DOCUMENT_ROOT /var/www/html/app/public
RUN sed -ri -e 's!/var/www/html!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/sites-available/*.conf
RUN sed -ri -e 's!/var/www/!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/apache2.conf /etc/apache2/conf-available/*.conf

COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

COPY composer.json php.ini ./

RUN composer install

RUN apt-get update && apt-get -y install libpq-dev

RUN docker-php-ext-install pdo_pgsql
